spring.application.name=project

server.port=8080
spring.profiles.active=dev

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

jwt.secret=${JWT_SECRET:8uw0rgjisehg0834gshfovaTvogaufgig08euTf5hg9a0whg9hcivbetGRgore0geogejrgd}
jwt.access-token-minutes=30
jwt.refresh-token-days=7
